# Scans the "photos" folder and regenerates photos.js for gallery.html.
# Run this after adding/removing photos:  right-click -> Run with PowerShell
$root   = Split-Path -Parent $MyInvocation.MyCommand.Path
$photos = Join-Path $root 'photos'
$exts   = '.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.bmp'

if (-not (Test-Path $photos)) { New-Item -ItemType Directory $photos | Out-Null }

$files = Get-ChildItem $photos -File |
         Where-Object { $exts -contains $_.Extension.ToLower() } |
         Sort-Object Name |
         ForEach-Object { '  "photos/' + $_.Name + '"' }

$content = "// Auto-generated by update-photos.ps1 - do not edit by hand.`n" +
           "window.PHOTOS = [`n" + ($files -join ",`n") + "`n];`n"

Set-Content -Path (Join-Path $root 'photos.js') -Value $content -Encoding utf8
Write-Host ("photos.js updated with {0} photo(s)." -f @($files).Count)
