# Scans the "photos" folder and regenerates photos.js for index.html.
#
# Your original files are NEVER modified. For each photo a fast preview
# (max 1600px, JPEG q88) is generated into photos\_preview — the 3D scene
# loads the preview; clicking a photo fullscreen loads your untouched
# original at full resolution.
#
# Run this after adding/removing photos:  right-click -> Run with PowerShell

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root    = Split-Path -Parent $MyInvocation.MyCommand.Path
$photos  = Join-Path $root 'photos'
$prevDir = Join-Path $photos '_preview'
$exts    = '.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.bmp'
$decodable = '.jpg', '.jpeg', '.png', '.gif', '.bmp'   # formats System.Drawing can read
$MAXEDGE = 1600
$QUALITY = 88

if (-not (Test-Path $photos))  { New-Item -ItemType Directory $photos  | Out-Null }
if (-not (Test-Path $prevDir)) { New-Item -ItemType Directory $prevDir | Out-Null }

function New-Preview([System.IO.FileInfo]$file, [string]$outPath) {
    $img = [System.Drawing.Image]::FromFile($file.FullName)
    try {
        # respect EXIF orientation (0x0112) so previews aren't sideways
        if ($img.PropertyIdList -contains 0x0112) {
            $o = $img.GetPropertyItem(0x0112).Value[0]
            switch ($o) {
                3 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate180FlipNone) }
                6 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate90FlipNone) }
                8 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone) }
            }
        }
        $long = [Math]::Max($img.Width, $img.Height)
        if ($long -le $MAXEDGE) { return $false }   # already small -> just use the original

        $scale = $MAXEDGE / $long
        $w = [int]([Math]::Round($img.Width  * $scale))
        $h = [int]([Math]::Round($img.Height * $scale))

        $bmp = New-Object System.Drawing.Bitmap($w, $h)
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.InterpolationMode  = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.SmoothingMode      = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
        $g.DrawImage($img, 0, 0, $w, $h)
        $g.Dispose()

        $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
                 Where-Object { $_.MimeType -eq 'image/jpeg' }
        $ep = New-Object System.Drawing.Imaging.EncoderParameters(1)
        $ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter(
                         [System.Drawing.Imaging.Encoder]::Quality, [long]$QUALITY)
        $bmp.Save($outPath, $codec, $ep)
        $bmp.Dispose()
        return $true
    }
    finally { $img.Dispose() }
}

$files = Get-ChildItem $photos -File |
         Where-Object { $exts -contains $_.Extension.ToLower() } |
         Sort-Object Name

$entries = @()
$made = 0
foreach ($f in $files) {
    $full = 'photos/' + $f.Name
    $prevName = [System.IO.Path]::GetFileNameWithoutExtension($f.Name) + '.jpg'
    $prevPath = Join-Path $prevDir $prevName
    $prevRel  = 'photos/_preview/' + $prevName

    $hasPreview = $false
    if ($decodable -contains $f.Extension.ToLower()) {
        if ((Test-Path $prevPath) -and ((Get-Item $prevPath).LastWriteTime -gt $f.LastWriteTime)) {
            $hasPreview = $true    # up to date, skip regeneration
        }
        else {
            try {
                $hasPreview = New-Preview $f $prevPath
                if ($hasPreview) { $made++ }
            } catch { Write-Warning ("Could not create preview for {0}: {1}" -f $f.Name, $_.Exception.Message) }
        }
    }

    if ($hasPreview) { $entries += ('  { s: "' + $prevRel + '", f: "' + $full + '" }') }
    else             { $entries += ('  "' + $full + '"') }
}

$content = "// Auto-generated by update-photos.ps1 - do not edit by hand.`n" +
           "// s = fast preview shown in the 3D scene, f = untouched full-res original (fullscreen).`n" +
           "window.PHOTOS = [`n" + ($entries -join ",`n") + "`n];`n"

Set-Content -Path (Join-Path $root 'photos.js') -Value $content -Encoding utf8
Write-Host ("photos.js updated: {0} photo(s), {1} new preview(s) generated." -f @($files).Count, $made)
